version: "3.2"
services:
  postgres:
    image: postgres:14
    hostname: postgres
    container_name: tas-frontend-challenge-postgres
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./external-tools/postgres:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
  #  web:
  #    container_name: web
  #    build:
  #      context: .
  #      dockerfile: ./apps/demo-app/Dockerfile
  #    restart: always
  #    ports:
  #      - 9000:9000
  tas-api:
    container_name: tas-api
    build:
      context: .
      dockerfile: ./apis/demo-api/Dockerfile
    restart: always
    ports:
      - 10000:10000
